apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: public.ecr.aws/l1b1a8r4/voting-app-vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
